# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_contact2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact2',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
