# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_contact2_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact2',
            name='photo',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='page/static/pic_folder/'),
        ),
    ]
