# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20171029_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
