# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact2',
            new_name='Contact',
        ),
    ]
