# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20171029_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodinne_Domy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('screen', models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='page/static/screen_folder/')),
            ],
        ),
    ]
