# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_rodinne_domy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodinne_domy',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
