# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_rodinne_domy_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodinne_Domy_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='photo_folder/None/no-img.jpg', upload_to='page/static/photo_folder/')),
                ('rodinny_dum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Rodinne_Domy')),
            ],
        ),
    ]
