# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_rodinne_domy_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rodinne_Domy',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Rodinne_Domy_Photo',
            new_name='Project_Photo',
        ),
    ]
