# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20171117_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vizualizace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('screen', models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='page/static/screen_folder/')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vizualizace_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(default='photo_folder/None/no-img.jpg', upload_to='page/static/photo_folder/')),
                ('vizualizace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Vizualizace')),
            ],
        ),
    ]
