# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_auto_20171129_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
