# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20171215_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_photo',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
