# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_project_photo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_photo',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
