# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20180106_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
