# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0024_auto_20180312_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screen',
            field=models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='screen_folder/'),
        ),
        migrations.AlterField(
            model_name='vizualizace',
            name='screen',
            field=models.ImageField(default='screen_folder/None/no-img.jpg', upload_to='vizualizace_folder/'),
        ),
    ]
